### ISSUE TITLE
Add lexido to the Arch User Repository

### ISSUE THREAD

**Issue by micr0-dev** [micr0-dev/lexido#10]
This would allow for a greater reach of the project and easier installs and updates.

**Comment by Emberzo** [comment]
https://gist.github.com/keilmillerjr/dbfd9d60b2cd5fb440274c0a67a7db18

this might help you make one

**Comment by micr0-dev** [comment]
I know how to make one, I would just prefer to not be the maintainer of the Package, thanks for the resource however whoever wants to give this a shot can use it

**Comment by Emberzo** [comment]
https://aur.archlinux.org/packages/lexido

**Comment by micr0-dev** [comment]
Great!! Thanks so much!
