### ISSUE TITLE
API not saving for zsh (v1.0.1)

### ISSUE THREAD

**Issue by Emberzo** [micr0-dev/lexido#15]
I have to put in the API key every time I use lexido

in my .zshrc file every time i run lexido it puts export GOOGLE_AI_KEY='MYKEY'

so if i run lexido two times I get this at the bottom of my .zshrc file

export GOOGLE_AI_KEY='MYKEY'

export GOOGLE_AI_KEY'MYKEY'

**Comment by Emberzo** [comment]
edited my .zrshrc file with nano and no for some reason it works sorry

**Comment by micr0-dev** [comment]
Everything is fixed? v1.0.1 no longer tries to save it as an environment variable, it's only used as a fallback. If there are any issues please let me know
