### ISSUE TITLE
AUR error (im fixing it right)

### ISSUE THREAD

**Issue by Emberzo** [micr0-dev/lexido#34]
**Describe the bug**
the error was caused by my Script that auto updates when a new version is uploaded and its mess up some PKGBUILD file ill fix it and update the AUR repo asap

wanted to post this here so people know that it is broken right now :)

**Comment by micr0-dev** [comment]
Alright, thanks for your help and for letting everyone know!

**Comment by Emberzo** [comment]
all fixed now my script was putting 2 vv in the github link and then looking for lexido-v1.2 not lexido-1.2 in the src files
