### ISSUE TITLE
tea.go error

### ISSUE THREAD

**Issue by Emberzo** [micr0-dev/lexido#35]
**Describe the bug**
# github.com/micr0-dev/lexido/pkg/tea
pkg/tea/tea.go:168:79: undefined: min
pkg/tea/tea.go:203:159: undefined: min
pkg/tea/tea.go:206:96: undefined: min
note: module requires Go 1.22

**To Reproduce**
git clone https://github.com/micr0-dev/lexido.git
cd lexido
./build-all.sh

**Expected behavior**
install without error

**Screenshots**
![image](https://github.com/micr0-dev/lexido/assets/113429324/5ef42357-ca30-4d90-ac5b-9df373da89ba)

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser Chrome
 - Version 1.2

**Additional context**

**Comment by micr0-dev** [comment]
["Starting with Go 1.21, min and max are available as builtins..."](https://stackoverflow.com/questions/27516387/what-is-the-correct-way-to-find-the-min-between-two-integers-in-go)

I believe your version of Golang is out of date specifically below version 1.21, also hinted at by this message:
```
note: module requires Go 1.22
```

Could you please provide the output of the following?
```sh
go version
```

**Comment by Emberzo** [comment]
my go version is go1.20.5 but i used it the other day and was fine did 1.22 just come out?

**Comment by Emberzo** [comment]
even after sudo pacman -Syu go i still have go version go1.20.5 linux/amd64
ill try use gvm to install 1.22

**Comment by micr0-dev** [comment]
Try running
```sh
which go
```
to see the path of the go binary that is being executed, that might help you find out what is interfering.

**Comment by micr0-dev** [comment]
It may be that another go project you installed may have downgraded to go 1.20 therefore caused this issue

**Comment by Emberzo** [comment]
i got go version go1.22.0 linux/amd64 by installing it via gvm and then uninstalling go via pacman and then set the path to go on my .bashrc file ill test the install again to see if this has made it work

**Comment by Emberzo** [comment]
it works now i have no idea what downgraded my go version but gvm helped me get it to 1.22
