### ISSUE TITLE
Windows Version when

### ISSUE THREAD

**Issue by VolumeCheese** [micr0-dev/lexido#41]
**Is your feature request related to a problem? Please describe.**
Im frustrated when i want to concatenate mp4s with ffmpeg but i cant because im too stupid to do it by myself...

**Describe the solution you'd like**
make a windows version 🥺🥺

**Describe alternatives you've considered**
Me switch to linux 🤮🤮🤮

**Additional context**
penis

**Comment by VolumeCheese** [comment]
@micr0-dev

**Comment by micr0-dev** [comment]
I will look into this, however I do not have a windows machine to test it on, I may be able to setup a VM but I would still need someone to actually test it on a functional windows machine

**Comment by Just-a-Unity-Dev** [comment]
I'm fairly sure you can just compile the source code by yourself

**Comment by micr0-dev** [comment]
You probably can, I can't guarantee if it will work though

**Comment by Emberzo** [comment]
![image](https://github.com/micr0-dev/lexido/assets/113429324/f5288aac-e75a-4f6c-9190-3227cbeb1cee)

lexido works on windows you got to build it using go build like some linux distros at the moment 
(one slow ass office pc ik don't worry about it lmao).

I'm not sure how to make it work without having the exe in the same file as your current file as im a windows noob.

EDIT: forgot to say you have to manually make a folder in 
C:\Users\<username>\.lexido
and then make a file called keyring.json
and put this in it 
`
{
    "GOOGLE_AI_KEY": "",
    "OLLAMA_MODEL": "",
    "OLLAMA_LOCAL": "false"
}
`

after doing that you will get asked to enter a API key or you can see if ollama works on windows and use that.
