### ISSUE TITLE
The path of go should not be hard coded in PKGBUILD

### ISSUE THREAD

**Issue by stormckey** [micr0-dev/lexido#45]
The go path in PKGBUILD may be wrong ,at least for me

I just ran `yay -S lexido` and ran into the error below

![image](https://github.com/micr0-dev/lexido/assets/109893671/4496b7a9-750b-4cd8-8f30-301d118499ea)

**Comment by micr0-dev** [comment]
@Swayz8148

**Comment by micr0-dev** [comment]
Sorry for the delay guys, I don't maintain the package on the AUR, could you also post it in the AUR comments or something so the maintainer of the PKGBUILD can fix it?

**Comment by Emberzo** [comment]
will be fixed by the morning sorry about this

**Comment by micr0-dev** [comment]
No worries!

**Comment by Emberzo** [comment]
Fixed it if theres still any errors please @ me again 👍

**Comment by micr0-dev** [comment]
I tried installing and it seemed to work, thanks for the fix! I will close this now, but if anyone else still has issues please re-open!
