### ISSUE TITLE
An error occurred: proto: (line 34:3): unknown field "usageMetadata"

### ISSUE THREAD

**Issue by fvkd** [micr0-dev/lexido#63]
Getting this error after every command: 

> An error occurred: proto: (line 34:3): unknown field "usageMetadata"

**Comment by micr0-dev** [comment]
Can you provide a little bit more info? 

What system? 

When is it happening? Each time you run the lexido command? Or each time it runs commands? If it is the latter what commands cause that error?

**Comment by micr0-dev** [comment]
Could not reproduce, not enough info.

**Comment by micr0-dev** [comment]
Actually fixed with generative-ai-go@v0.11.1 [https://github.com/google/generative-ai-go/issues/97](https://github.com/google/generative-ai-go/issues/97)

**Comment by micr0-dev** [comment]
Please try the v1.4.1 release
