### ISSUE TITLE
The tool forgets the API key.

### ISSUE THREAD

**Issue by XenowoAct** [micr0-dev/lexido#7]
I always get prompted to enter an API key even though I restart my terminal after entering it the first time.

**Comment by micr0-dev** [comment]
Could you please provide your operating system and terminal shell?

**Comment by micr0-dev** [comment]
I ask about the shell because the way it saves it is an environment variable that is put into your .bashrc or .zshrc.

**Comment by XenowoAct** [comment]
Thank you for getting back! I am using bash on Debian 12!

**Comment by micr0-dev** [comment]
Hopefully fixed with #9, please try the latest v1.0.1 release!

**Comment by XenowoAct** [comment]
That did, indeed fix the issue! Thank you very much!
